version: '3.3'

services:
  django_gunicorn:
    volumes:
      - static:/static
    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django_gunicorn

volumes:
  static: